extends Node

var english = {
"all":
[
["Stay still until the sharks go away.","Change boat’s route to diverge from sharks.","Attack the sharks to kill them.","The boat shakes with waves that got out of nowhere. Something is moving closer to the boat, down the water. The children are curious about it. Maybe those are dolphins? Adults are frightened. They might be in danger. A woman screams and holds her baby tight: “it’s a shark!”. Then two sailors begin to argue, one says that the gotta fight the creature right away to save their lives: “it’s us or them”. The other sailor advices: “stay calm and silent. Stop moving the boat. They will not attack if we do not look like a threat to them”."],
["Greet back and tell him about what direction you are heading to.","Greet back and tell him about the pregnant woman.","Greet back and tell him you are hungry.","There’s a pregnant woman in pain into the boat and everyone is already hungry. Looks like they did not take enough supplies to a long journey. Refugees thought the crossing would take a few hours, not days. A fisher nearby the boat gives them friendly greetings."],
["Hold tight to the boat and wait.","Go downstairs.","Try to take the water out of the boat.","The sky gets so bright it’s blinding. A loud thunder resonates. It’s blustering. Children all over the boat tremble in fear. Then the storm begins. Rain, wind, lightning, thunder: all at once, violently. Water pours inside it from the sky. Everyone and everything on the top of it is getting soaked fastly. The boat is shaking. The engine gets noisy. Sailor are making extra effort to conduct the boat, moving carefully. Some refugees starts praying and others crying. The path to their freedom might be tough, but something might be done in order to overcome the storm."],
["Dodge the iceberg","Stop abruptly","Keep going","It’s difficulty to see the ocean in their front. Fog has taken over the horizon. When they finally notice the big ice block in front of the boat, it’s just a few meters away. If the Titanic has been taken down by an iceberg, could the refugees survive it?"],
["Systematically answer to the guards questions, with honesty.","Explain that you are running away from your country to ask for shelter at Apué.","Ask for help and information.","The fort’s sirens starts to sound. The guard talks through the speaker “Identifications, please! Where did you came from? Do you have passport and visa?”"],
["Ask for food and medicine before going away “Don’t worry, we are not willing to stay here. Yet the voyage is taking longer than we thought, we are out of food, water and everything else. Could you please help us with some resources? We can’t even go back in this condition”, for sure the refugee is bluffing about going back.","Ask about their final destination distance and direction “Excuse me, we are trying to dock at Apué. Are we near? Where is it?”","Explain that it’s a matter of life or death and you are on the sea for weeks, running away from bad human conditions: “going back is dying” and ask for asylum.","The coaster police says “There’s no space for unauthorized immigrants like you here. You can’t dock! I highly recommend that you get back to your own land!”"],
["Let all the adrift group into your boat.","Let most vulnerable ones get onboard.","Try to fix their boat.","A small boat gets in their eyesight. It’s full of scared people that start to ask for help. Taking a closer look it gets clear that the small boat is crashed, water is getting inside. It’s another group of refugees, coming from another devastated country and heading to the same destination."],
["Move refugees from the bottom to the top of the boat so that they can stay away from the engine’s heat.","Do nothing. Engines are hot, that’s normal.","Turn off the engine and try to fix it.","Something is wrong with the engine, it starts to heat. People on the bottom of the boat can barely breath"],
["Find the sick refugees and throw them out of the boat before the disease spreads and kills everyone.","Use medicine.","Do nothing.","After many days travelling, cough and sneeze are frequent among refugees. Someone might have boarded with some kind of disease. Who was it?"],
["Look at the water.","Don’t look at the water.","Go fishing.","Suddenly the ocean gets peaceful. Something is moving softly under the water. Curiosity takes over everyone. What was that?"],
["Increase boat’s speed and try to go through this windy area faster.","Sail to the same direction the wind is blowing to.","Reduce boat’s speed and keep it safe and stable.","The wind speed increases and the sea gets furious forming tremendous waves. The boat starts to swing with the surge and water is splashing inside the boat. Refugees are frightened."],
["Stop the boat, turn off the lights and try to not be seen.","Move faster and try to get away.","Pirates only exists in fairy tales (ignore).","Looking through binoculars a child sees an old wooden vessel, with a black flag in the mast. There’s only one thing a ship like that can be: “Pirates at sight!”"],
["Hold tight to the boat and pray.","Attack whatever is below the water.","Try to “surf” the wave.","A weird wave is coming in the boat’s direction. Something seems to be moving bellow it."]
]
}

var french ={
"all":
[
["Restez immobile jusqu'à ce que les requins s'en aillent..","Changez la route du bateau pour s'écarter des requins.","Attaquez les requins pour les tuer."," Le bateau tremble avec des vagues qui viennent de nulle part. Quelque chose se rapproche du bateau, dans l'eau. Les enfants sont curieux à ce sujet. Peut-être que ce sont des dauphins? Les adultes ont peur. Ils pourraient être en danger. Une femme crie et serre son bébé dans ses bras: “c’est un requin!”. Puis deux marins commencent à se disputer, l’un dit qu’il faut tout de suite combattre la créature pour sauver leur vie: “c’est nous ou eux”. L’autre marin conseille: “restez calme et silencieux. Arrêtez de déplacer le bateau. Ils n'attaqueront pas si nous ne leur semblons pas une menace”."],
["Répondez-lui et dites-lui à quelle direction vous allez.","Saluez et informez de la femme enceinte.","Saluez et informer que vous avez faim.","Une femme enceinte souffre dans le bateau et tout le monde a déjà faim. On dirait qu'ils n'ont pas pris assez de fournitures pour un long voyage. Les réfugiés pensaient que la traversée prendrait quelques heures, pas plusieurs jours. Un pêcheur à proximité du bateau leur transmet ses salutations amicales.."],
["Tenez fermement le bateau et attendez.","Descendez.","Essayez de prendre l'eau du bateau.","Le ciel est tellement brillant qu’il est aveuglant. Un tonnerre fort résonne. C’est cinglant. Les enfants partout sur le bateau tremblent de peur. Alors la tempête commence. Pluie, vent, éclairs, tonnerre: tout à la fois, violemment. L'eau coule à l'intérieur du ciel. Tout le monde et tout ce qu'il y a dessus deviennent rapidement trempés. Le bateau tremble. Le moteur devient bruyant. Les marins font des efforts supplémentaires pour conduire le bateau, en se déplaçant avec précaution. Certains réfugiés commencent à prier et d'autres à pleurer. La voie vers leur liberté peut être difficile, mais quelque chose pourrait être fait pour surmonter la tempête."],
["Esquivez l'iceberg","Arrêtez brusquement","Continuez","C’est difficile de voir l’océan devant eux. Le brouillard a envahi l'horizon. Quand ils remarquent enfin le gros bloc de glace devant le bateau, il n’est plus qu’à quelques mètres. Si le Titanic a été abattu par un iceberg, les réfugiés pourraient y survivre?"],
["Répondez systématiquement aux questions des gardes, avec honnêteté.","Expliquez que vous fuyez votre pays pour demander un abri à Apué.","Demandez de l'aide et des informations.","Les sirènes du fort commencent à se déclencher du son. Le gardien parle par le biais de l'intervenant “Des identifications, s'il vous plaît! D'où venez-vous? Avez-vous un passeport et un visa?”"],
["Demandez de la nourriture et des médicaments avant de partir “Ne vous inquiétez pas, on ne veut pas rester ici. Pourtant, le voyage prend plus de temps que prévu, nous manquons de nourriture, d’eau et de tout le reste. Pourriez-vous nous aider avec quelques ressources? On ne peut même pas rentrer dans cet état”, le réfugié bluffe pour son retour.","Renseignez-vous sur la distance et la direction de leur destination finale. “Excusez-moi, nous essayons d'accoster à Apué. On est près? C’est où?”","Expliquez que c’est une question de vie ou de mort et que vous passez plusieurs semaines sur la mer, à fuir de mauvaises conditions humaines: “rentrer, c'est mourir” et demander l’asile.","La police des montagnes a déclaré: “Ici, il n’ya pas de place pour les immigrants non autorisés comme vous. Vous ne pouvez pas accoster! Je vous recommande vivement de revenir sur votre propre terre!"],
["Laissez tout le groupe à la dérive dans votre bateau.","je. Laissons les plus vulnérables embarquer.","Essayez de réparer leur bateau.","Un petit bateau entre dans la vue. C’est plein de gens effrayés qui commencent à demander de l’aide. En regardant de plus près, on s'aperçoit que le petit bateau est écrasé et que l'eau pénètre à l'intérieur. C’est un autre groupe de réfugiés, venant d’un autre pays dévasté et se dirigeant vers la même destination."],
["Déplacez les réfugiés du bas vers le haut du bateau afin qu’ils puissent rester à l’écart de la chaleur du moteur","Ne faites rien. Les moteurs sont chauds, c’est normal.","Eteignez le moteur et essayez de le réparer.","Quelque chose ne va pas avec le moteur, il commence à chauffer. Les gens au fond du bateau peuvent à peine respirer."],
["Trouvez les réfugiés malades et jetez-les du bateau avant que la maladie ne se propage et ne tue tout le monde.","Utilisez des médicaments.","Ne faites rien.","Après plusieurs jours de voyage, la toux et les éternuements sont fréquents chez les réfugiés. Quelqu'un aurait pu embarquer avec une sorte de maladie. Qu’est-ce que c’était?"],
["Regarde l'eau.","Ne regardez pas l’eau","Aller pêcher.","Soudainement, l'océan se calme. Quelque chose bouge doucement sous l'eau. La curiosité envahit tout le monde. Ça c'était quoi?"],
["Augmentez la vitesse du bateau et essayez de traverser cette zone venteuse plus rapidement.","Naviguez dans la même direction que le vent.","Réduisez la vitesse du bateau et gardez-le en sécurité et stable.","La vitesse du vent augmente et la mer devient furieuse, formant d'énormes vagues. Le bateau commence à se balancer avec la montée subite et de l'eau éclabousse à l'intérieur du bateau. Les réfugiés ont peur."],
["Arrêtez le bateau, éteignez les lumières et essayez de ne pas être vu.","Avancez plus vite et essayez de vous échapper.","Les pirates n'existent que dans les contes de fées (ignorez).","En regardant à travers des jumelles, un enfant voit un vieux bateau en bois avec un drapeau noir dans le mât. Un navire comme celui-ci ne peut avoir qu’une chose: 'Des pirates à vue!'"],
["Tenir fermement le bateau et prier.","Attaquez tout ce qui est en dessous de l'eau.","Essayez de 'surfer' la vague.","Une vague étrange arrive dans la direction du bateau. Quelque chose semble bouger en dessous."]
]
}



